In [ ]:
import random
def validate(hand):
    if hand>2 or hand<0:
        return False
    return True
        
def print_hand(hand,name="ゲスト"):
    hands=["グー","チョキ","パー"]
    print(name+"は"+hands[hand]+"を出しました")

def judge(player,computer):
    if player == computer:
        return '引き分け'
    elif player == 0 and computer == 1:
        return '勝ち'
    elif player == 1 and computer == 2:
        return '勝ち'
    elif player == 2 and computer == 0:
        return '勝ち'
    else:
        return '負け'
    
i=0
print("じゃんけんを開始します")
player_name=input("名前を入力してください:")
for i in range(100):
    
    print("出す手を選んでください。グー：０、チョキ：１、パー：２：")
    player_hand=int(input("数字で入力してください:"))

    if validate(player_hand):
        computer_hand=random.randint(0,2)
        if player_name=="":
            print_hand(player_hand)
        else:
            print_hand(player_hand,player_name)
        print_hand(computer_hand,"コンピューター")
        result=judge(player_hand,computer_hand)
        if result=="引き分け":
            print("あいこでしょ")
        else:
            print("結果は"+result+"でした")
            break
    else:
        print("正しい値を入力してください")

In [ ]:
import random
def validate(hand):
    if hand>2 or hand<0:
        return False
    return True
        
def print_hand(hand,name="ゲスト"):
    hands=["グー","チョキ","パー"]
    print(name+"は"+hands[hand]+"を出しました")

def judge(player,computer):
    if player == computer:
        return '引き分け'
    elif player == 0 and computer == 1:
        return '勝ち'
    elif player == 1 and computer == 2:
        return '勝ち'
    elif player == 2 and computer == 0:
        return '勝ち'
    else:
        return '負け'
    
i=0
x=0
print("じゃんけんを開始します、１００回以内に2回勝ってください")
player_name=input("名前を入力してください:")
for i in range(100):
    
    print("出す手を選んでください。グー：０、チョキ：１、パー：２：")
    player_hand=int(input("数字で入力してください:"))

    if validate(player_hand):
        computer_hand=random.randint(0,2)
        if player_name=="":
            print_hand(player_hand)
        else:
            print_hand(player_hand,player_name)
        print_hand(computer_hand,"コンピューター")
        result=judge(player_hand,computer_hand)
        if result=="引き分け":
            print("あいこです")
        else:
            print("結果は"+result+"でした")
            if result=="勝ち":
                x+=1
            else:
                x+=0
            if x>=2:
                print("2回勝利したのであなたの勝ちです")
                break
            else:
                print("まだ2回勝利していません")
                print("------------------------------------------------------------")
    else:
        print("正しい値を入力してください")

In [5]:
import random
def validate(hand):
    if hand>2 or hand<0:
        return False
    return True
        
def print_hand(hand,name="ゲスト"):
    hands=["グー","チョキ","パー"]
    print(name+"は"+hands[hand]+"を出しました")

def judge(player,computer):
    if player == computer:
        return '引き分け'
    elif player == 0 and computer == 1:
        return '勝ち'
    elif player == 1 and computer == 2:
        return '勝ち'
    elif player == 2 and computer == 0:
        return '勝ち'
    else:
        return '負け'
    
i=0
x=0
print("じゃんけんを開始します、１００回以内に2回連続で勝ってください")
player_name=input("名前を入力してください:")
for i in range(100):
    
    print("出す手を選んでください。グー：０、チョキ：１、パー：２：")
    player_hand=int(input("数字で入力してください:"))

    if validate(player_hand):
        computer_hand=random.randint(0,2)
        if player_name=="":
            print_hand(player_hand)
        else:
            print_hand(player_hand,player_name)
        print_hand(computer_hand,"コンピューター")
        result=judge(player_hand,computer_hand)
        if result=="引き分け":
            print("あいこです")
        else:
            print("結果は"+result+"でした")
            if result=="勝ち":
                x+=1
            else:
                x*=0
            if x>=2:
                print("2回連続で勝利したのであなたの勝ちです")
                break
            else:
                print("まだ2回連続勝利していません")
                print("------------------------------------------------------------")
    else:
        print("正しい値を入力してください")

じゃんけんを開始します、１００回以内に2回連続で勝ってください
名前を入力してください:sy
出す手を選んでください。グー：０、チョキ：１、パー：２：
数字で入力してください:1
syはチョキを出しました
コンピューターはパーを出しました
結果は勝ちでした
まだ2回連続勝利していません
------------------------------------------------------------
出す手を選んでください。グー：０、チョキ：１、パー：２：
数字で入力してください:2
syはパーを出しました
コンピューターはグーを出しました
結果は勝ちでした
2回連続で勝利したのであなたの勝ちです


In [ ]:
x=1
for i in range(30):
    #import sys　をして　xrange(int(sys.argv[1]))で無限？
    if x%3==0 and x%5!=0:
        print("Fizz")
    elif x%5==0 and x%3!=0:
        print("Buzz")
    elif x%3==0 and x%5==0:
        print("FizzBuzz")
    else:
        print(x)
    x+=1

In [43]:
def heihoukon(number):
    return number**(1/2)
xx=int(input("数字で入力してください:"))
heihoukon(xx)

数字で入力してください:1


1.0

In [105]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6,7,8,9,10,11,12,13,14,15,16,17])
type(x)
a=x
b=y.copy()
a[0]=100
b[0]=100
print(x)
print(y)
z=np.array([[1,2,3],[4,5,6]])
print(z[0,2])
print(np.sqrt(64))
print(np.round(1.75947,4))
print(np.log(8))
print(np.mean(100))
c=np.arange(50)
print(c[44:14:-3])
y[y>10]=999
print(y)
data=np.random.randn(5)
print(data)
np.save(datafile.npy,data)
data=[]
print(data)
data=np.load("datafile.npy")
print(data)

[100   2   3]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17]
3
8.0
1.7595
2.07944154168
100.0
[44 41 38 35 32 29 26 23 20 17]
[  4   5   6   7   8   9  10 999 999 999 999 999 999 999]
[ 1.2247591  -0.03410171  0.66475013  0.12185622 -0.36985148]


TypeError: 'tuple' object is not callable

In [67]:
f=open("read1.txt.ipynb","r")

for row in f:
    print(row)
    
f.close()

{

 "cells": [

  {

   "cell_type": "code",

   "execution_count": 2,

   "metadata": {},

   "outputs": [

    {

     "ename": "NameError",

     "evalue": "name 'Python' is not defined",

     "output_type": "error",

     "traceback": [

      "\u001b---------------------------------------------------------------------------\u001b",

      "\u001bNameError\u001b                                 Traceback (most recent call last)",

      "\u001b<ipython-input-2-bea1074c8f6a>\u001b in \u001b<module>\u001b()\u001b\n\u001b----> 1\u001b \u001bPython\u001b\u001b\u001b\u001b\n\u001b",

      "\u001bNameError\u001b: name 'Python' is not defined"

     ]

    }

   ],

   "source": [

    "Python"

   ]

  }

 ],

 "metadata": {

  "kernelspec": {

   "display_name": "Python 3",

   "language": "python",

   "name": "python3"

  },

  "language_info": {

   "codemirror_mode": {

    "name": "ipython",

    "version": 3

   },

   "file_extension": ".py",

   "mimetype": "text/x-python",

  